sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode8.1
    # See also: https://github.com/Homebrew/homebrew-core/issues/6949
  - os: linux
    language: python
    python: pypy-5.3.1
  - os: linux
    language: python
    python: 2.6
  - os: linux
    language: python
    python: 2.7
  - os: linux
    language: python
    python: 3.3
  - os: linux
    language: python
    python: 3.4
  - os: linux
    language: python
    python: 3.5
  - os: linux
    language: python
    python: 3.6
install:
  |
  if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    pip install --upgrade pip setuptools tox-travis;
  elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    brew tap drolando/homebrew-deadsnakes;
    brew install python33 python34 python35 python3 pypy
    pip install --upgrade pip setuptools
    pip install --user tox;
  fi
script: tox
