matrix:
  include:
  - os: osx
    osx_image: xcode8.1
    # See also: https://github.com/Homebrew/homebrew-core/issues/6949
  - os: linux
    language: python
    python: pypy-5.3.1
  - os: linux
    language: python
    python: 2.7
  - os: linux
    language: python
    python: 3.4
  - os: linux
    language: python
    python: 3.5
  - os: linux
    language: python
    python: 3.6
  - os: linux
    dist: xenial  # Python 3.7 is currently only supported by xenial dist
    sudo: true
    language: python
    python: 3.7
    env:
    - DEPLOY=true
    # PYPI_USER, PYPI_PASSWORD:
    - secure: "RuuxHmBSalNkE8/hwYgARkv15cYVECyuj/+rPTBl/xjL7lBXxBPjqSDb224sSt8gQw+tjfCPZ0C4oum1SY82kFLKOY2KuYwZcb+F6MMsL8BaHKi8LubGkaX08DGQDxwQijsqPjxfSLHPkqaw7M76EnOpnrKmbwKQ1PMLvknABG6CfWTpoGcrBFrkgLOxAsHzMW/RywjvlP4S1vRi34Iv4+zzjVDYGMRVk3Wrs+whzTgf0EJDlYMBrvHXisSJbcKtlgSay+g0aqg9JSSFxcYrPQEYZSHJSs5+QTyhVKTSD6tDTYqFwRYEa1SKz+A6MVb6yxRik7vvScdH/AZCaon66EfNZUGLMG9P3jY956rP3nWcHG2G/NuObXc5Ol5ilRKgztWiyG5zXZf4GqVMHbwfO2Z6ek5FrPWEmCM+UD7JvbU4tG6u7lTx0bLgvzE1Gc67bEGCYoTSSPXTyKXO3V/bT5TR6hPI4BkuaTLDuF1LHIoxiW7TsxuPApra2vClLdEe+sJ6elz+8MN9dk6WFpCYTZdusIY+Tle8RuEzC6TaR2eQ+jl9z1GI+kvV1Z494Em3RzSz0/daB1rQCC/cJsXnhXjG6XkthR42nAVGaXBmdlcRBI/qvJt0VZP2aO73GTFLkBczS+rID+KJxn12t8R4UHd3iPVqw67c9vSEqrg7lpI="

install:
  |
  if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    pip install --upgrade pip setuptools
    pip install --upgrade tox-travis docutils twine
  elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    brew update || true
    brew upgrade || true
    brew update || true
    brew tap drolando/homebrew-deadsnakes
    brew install python33 python34 python35 python3 pypy
    pip3 install --upgrade pip setuptools
    pip3 install --user tox docutils
  fi
script:
- |
  if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    export PATH="$(python3 -m site --user-base)/bin:$PATH"
  fi
  tox -- -O --github-access-token="$GITHUB_ACCESS_TOKEN"
  tox -e lint
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
- '[[ "$TRAVIS_TAG" = "" ]] || grep "Version $TRAVIS_TAG" README.rst'
- '[[ "$TRAVIS_OS_NAME" = "osx" ]] || [[ "$TRAVIS_TAG" = "" ]] || ! grep -i "to be released" README.rst'
after_success:
- 'rm -rf build/ dist/ fzf-*.json iterfzf/fzf iterfzf/fzf.exe'
- python setup.py sdist
- 'echo >> setup.cfg'
- 'echo "[bundle_fzf]" >> setup.cfg'
- 'echo "github-access-token = $GITHUB_ACCESS_TOKEN" >> setup.cfg'
- python setup.py bundle_fzf -p linux   -a 386   bdist_wheel
- python setup.py bundle_fzf -p linux   -a amd64 bdist_wheel
- python setup.py bundle_fzf -p freebsd -a 386   bdist_wheel
- python setup.py bundle_fzf -p freebsd -a amd64 bdist_wheel
- python setup.py bundle_fzf -p openbsd -a 386   bdist_wheel
- python setup.py bundle_fzf -p openbsd -a amd64 bdist_wheel
- python setup.py bundle_fzf -p darwin  -a 386   bdist_wheel
- python setup.py bundle_fzf -p darwin  -a amd64 bdist_wheel
- python setup.py bundle_fzf -p windows -a 386   bdist_wheel
- python setup.py bundle_fzf -p windows -a amd64 bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm5  bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm6  bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm7  bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm8  bdist_wheel
deploy:
- provider: releases
  api_key: "$GITHUB_ACCESS_TOKEN"
  file_glob: true
  file: dist/iterfzf-*.*
  skip_cleanup: true
  on:
    condition: '"$DEPLOY" = "true"'
    tags: true
after_deploy:
# We don't use Travis' PyPI provider since we shouldn't build dists twice
- 'echo "[pypi]" > ~/.pypirc'
- 'echo "username = $PYPI_USER" >> ~/.pypirc'
- 'echo "password = $PYPI_PASSWORD" >> ~/.pypirc'
- 'twine register dist/iterfzf-$TRAVIS_TAG.tar.gz || true'
- |
  for f in dist/iterfzf-*.*; do
    twine upload "$f";
  done
